### ISSUE TITLE
Integrate pose detection code with main website / robot animation page

### ISSUE THREAD

**Issue by rads560** [interaction-lab/PoseToCode#18]
- [x] dance
- [x] reset 
- [ ] place sphere animation is buggy
- [x] add run functionality by adjusting scene.js
- [x] integrate make sphere + sizes
- [ ] prompt user with 3, 2, 1 to choose a size
- [x] fix double run bug
- [x] fix bux where same code block appears several times

**Comment by nisha-chat** [comment]
- [x] dance
- [x] reset 
- [ ] make sphere + sizes
- [ ] fix issue where same code block appears several times
- [ ] add run functionality by adjusting scene.js
