### ISSUE TITLE
Create poses/actions for all code blocks

### ISSUE THREAD

**Issue by nisha-chat** [interaction-lab/PoseToCode#7]
- [x] Run code --> running motion
- [x] Dance --> raise the roof
- [x] Make sphere --> hands in front of chest
- [x] size of sphere --> right arm (low, med, high)
- [x] place sphere --> squat
- [x] reset --> x with hands

**Comment by rads560** [comment]
new bug: reset always also triggers make sphere (need to figure out how to fix this)
